import { Pipe, PipeTransform } from '@angular/core';

@Pipe({
  name: 'a3Format',
  standalone: true,
})
export class A3FormatPipe implements PipeTransform {
  /**
   * a3轉譯
   * @param value {string}-a3格式代碼
   * @returns {string}-轉譯後的數據欄位名
   */
  transform(value: string): string {
    switch (value) {
      case '1-0':
        return 'fileInfo';
      case '1-1':
        return 'type';
      case '1-2':
        return 'fileId';
      case '1-3':
        return 'creationDate';
      case '1-4':
        return 'creationUnixTimeStamp';
      case '1-5':
        return 'creationTimeZone';
      case '1-6':
        return 'createFrom';
      case '1-7':
        return 'countryRegion';
      case '1-8':
        return 'language';
      case '1-10':
        return 'syncDate';
      case '1-11':
        return 'dispName';
      case '1-12':
        return 'author';
      case '1-13':
        return 'editDate';
      case '1-14':
        return 'equipmentSN';
      case '1-15':
        return 'equipmentFwName';
      case '1-16':
        return 'equipmentFwCode';
      case '1-17':
        return 'equipmentHwName';
      case '1-18':
        return 'equipmentHwCode';
      case '1-19':
        return 'exampleFormat';
      case '1-20':
        return 'company';
      case '1-21':
        return 'alaFormatVersionName';
      case '1-22':
        return 'alaFormatVersionCode';
      case '1-23':
        return 'location';
      case '1-24':
        return 'photo';
      case '1-25':
        return 'video';
      case '1-26':
        return 'tag';
      case '1-27':
        return 'tagman';
      case '1-28':
        return 'note';
      case '1-29':
        return 'privacy';
      case '1-30':
        return 'teacher';
      case '1-31':
        return 'class';
      case '1-32':
        return 'brand';
      case '1-33':
        return 'branch';
      case '1-34':
        return 'uploadRawFileName';
      case '1-35':
        return 'cloudRunMapId';
      case '1-36':
        return 'fileGroupId';

      case '17-0':
        return 'activityInfoLayer';
      case '17-1':
        return 'type';
      case '17-4':
        return 'resolutionSeconds';
      case '17-5':
        return 'startTime';
      case '17-6':
        return 'pluginBluetoothSensorName';
      case '17-7':
        return 'pluginAntSensorName';
      case '17-8':
        return 'totalPoint';
      case '17-9':
        return 'totalLapOrSet';
      case '17-10':
        return 'totalActivityLapOrSet';
      case '17-11':
        return 'totalRestLapOrSet';
      case '17-12':
        return 'totalSecond';
      case '17-13':
        return 'totalActivitySecond';
      case '17-14':
        return 'totalRestSecond';
      case '17-15':
        return 'totalDistanceMeters';
      case '17-16':
        return 'elevGain';
      case '17-17':
        return 'elevLoss';
      case '17-18':
        return 'maxElev';
      case '17-19':
        return 'minElev';
      case '17-20':
        return 'avgElevGainSpeed';
      case '17-21':
        return 'maxElevGainSpeed';
      case '17-22':
        return 'avgElevLossSpeed';
      case '17-23':
        return 'maxElevLossSpeed';
      case '17-24':
        return 'calories';
      case '17-25':
        return 'avgHeartRateBpm';
      case '17-26':
        return 'maxHeartRateBpm';
      case '17-27':
        return 'avgSpeed';
      case '17-28':
        return 'maxSpeed';
      case '17-29':
        return 'avgMoveSpeed';
      case '17-30':
        return 'avgStrideLengthCentimeter';
      case '17-31':
        return 'totalStep';
      case '17-32':
        return 'runAvgCadence';
      case '17-33':
        return 'runMaxCadence';
      case '17-34':
        return 'stepAvgVerticalOscillation';
      case '17-35':
        return 'stepVerticalRatio';
      case '17-37':
        return 'cycleWheelDiameter';
      case '17-38':
        return 'totalRevolution';
      case '17-39':
        return 'cycleAvgCadence';
      case '17-40':
        return 'cycleMaxCadence';
      case '17-41':
        return 'cycleAvgWatt';
      case '17-42':
        return 'cycleMaxWatt';
      case '17-43':
        return 'totalStrokes';
      case '17-44':
        return 'swimAvgCadence';
      case '17-45':
        return 'swimMaxCadence';
      case '17-46':
        return 'poolLengthMeters';
      case '17-47':
        return 'poolSwimAvgCadence';
      case '17-48':
        return 'totalWeightKg';
      case '17-49':
        return 'totalReps';
      case '17-50':
        return 'weightTrainingInfo';
      case '17-51':
        return 'muscle';
      case '17-52':
        return 'max1RmWeightKg';
      case '17-53':
        return 'totalWeightKg';
      case '17-54':
        return 'totalSets';
      case '17-55':
        return 'totalReps';
      case '17-56':
        return 'useViceMuscle';
      case '17-57':
        return 'mets';
      case '17-58':
        return 'avgTemp';
      case '17-59':
        return 'maxTemp';
      case '17-60':
        return 'minTemp';
      case '17-61':
        return 'equipmentAvgResistanceWeightsKg';
      case '17-62':
        return 'equipmentMaxResistanceWeightsKg';
      case '17-63':
        return 'equipmentAvgIncline';
      case '17-64':
        return 'equipmentMaxIncline';
      case '17-65':
        return 'rowingAvgWatt';
      case '17-66':
        return 'rowingMaxWatt';
      case '17-67':
        return 'rowingAvgCadence';
      case '17-68':
        return 'rowingMaxCadence';
      case '17-69':
        return 'totalPulls';
      case '17-70':
        return 'gpsSensorStatus';
      case '17-71':
        return 'ohrSensorStatus';
      case '17-72':
        return 'gravitySensorStatus';
      case '17-73':
        return 'tempSensorStatus';
      case '17-74':
        return 'atmSensorStatus';
      case '17-75':
        return 'gyroSensorStatus';
      case '17-76':
        return 'complexActivity';
      case '17-77':
        return 'avgClimbInclineRatio';
      case '17-78':
        return 'max100mInclineRatio';
      case '17-79':
        return 'min100mInclineRatio';
      case '17-80':
        return 'avgSwolf';
      case '17-81':
        return 'bestSwolf';
      case '17-82':
        return 'totalHrZone0Second';
      case '17-83':
        return 'totalHrZone1Second';
      case '17-84':
        return 'totalHrZone2Second';
      case '17-85':
        return 'totalHrZone3Second';
      case '17-86':
        return 'totalHrZone4Second';
      case '17-87':
        return 'totalHrZone5Second';
      case '17-88':
        return 'totalElevGainSecond';
      case '17-89':
        return 'totalElevLossSecond';
      case '17-90':
        return 'resolutionMillisecondStatus';
      case '17-91':
        return 'userBodyWeight';
      case '17-92':
        return 'totalPlusGforceX';
      case '17-93':
        return 'totalPlusGforceY';
      case '17-94':
        return 'totalPlusGforceZ';
      case '17-95':
        return 'totalMinusGforceX';
      case '17-96':
        return 'totalMinusGforceY';
      case '17-97':
        return 'totalMinusGforceZ';
      case '17-98':
        return 'maxGforceX';
      case '17-99':
        return 'maxGforceY';
      case '17-100':
        return 'maxGforceZ';
      case '17-101':
        return 'miniGforceX';
      case '17-102':
        return 'miniGforceY';
      case '17-103':
        return 'miniGforceZ';
    }
  }
}
