import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { throwError, Observable, of } from 'rxjs';
import { catchError, switchMap } from 'rxjs/operators';
import { Api2104Post, Api2104Response } from '../models/api/api-21xx';

@Injectable({
  providedIn: 'root',
})
export class Api21xxService {
  constructor(private http: HttpClient) {}

  /**
   * api-v2 2102 取得運動資料列表
   * @param body {any}-api 所需參數
   */
  fetchSportList(body: any): Observable<any> {
    return <any>(
      this.http.post('/api/v2/sport/getSportList', body).pipe(catchError((err) => throwError(err)))
    );
  }

  /**
   * api-v2 2103 取得運動詳細資料
   * @param body {any}-api 所需參數
   */
  fetchSportListDetail(body: any): Observable<any> {
    return <any>(
      this.http
        .post('/api/v2/sport/getSportListDetail', body)
        .pipe(catchError((err) => throwError(err)))
    );
  }

  /**
   * api-v2 2104 取得運動資料概要陣列資料
   * @param body {any}-api 所需參數
   */
  fetchSportSummaryArray(body: Api2104Post): Observable<Api2104Response> {
    return this.http
      .post('/api/v2/sport/getSportSummaryArray', body)
      .pipe(catchError((err) => throwError(err))) as Observable<Api2104Response>;
  }

  /**
   * api-v2 2106 取得生活追蹤每日詳細資料
   * @param body {any}-api 所需參數
   */
  fetchTrackingDayDetail(body: any): Observable<any> {
    return <any>(
      this.http
        .post('/api/v2/sport/getTrackingDayDetail', body)
        .pipe(catchError((err) => throwError(err)))
    );
  }

  /**
   * api-v2 2107 取得生活追蹤概要陣列資料
   * @param body {any}-api 所需參數
   */
  fetchTrackingSummaryArray(body: any): Observable<any> {
    return <any>(
      this.http
        .post('/api/v2/sport/getTrackingSummaryArray', body)
        .pipe(catchError((err) => throwError(err)))
    );
  }

  /**
   * api-v2 2108 編輯活動資訊
   * @param body {any}-api 所需參數
   */
  fetchEditActivityProfile(body: any): Observable<any> {
    return <any>(
      this.http
        .post('/api/v2/sport/editActivityProfile', body)
        .pipe(catchError((err) => throwError(err)))
    );
  }

  /**
   * api-v2 2109 刪除活動或生活追蹤資料
   * @param body {any}-api 所需參數
   */
  fetchDeleteActivityData(body: any): Observable<any> {
    return <any>(
      this.http
        .post('/api/v2/sport/deleteActivityData', body)
        .pipe(catchError((err) => throwError(err)))
    );
  }

  /**
   * api-v2 2111 依條件需求取得多筆運動檔案
   * @param body {any}-api 所需參數
   */
  fetchMultiActivityData(body: any): Observable<any> {
    return <any>(
      this.http
        .post('/api/v2/sport/getMultiActivityData', body)
        .pipe(catchError((err) => throwError(err)))
    );
  }

  /**
   * api-v2 2114 編輯運動或生活追蹤檔案及報告隱私權
   * @param body {any}-api 所需參數
   */
  fetchEditPrivacy(body: any): Observable<any> {
    return <any>(
      this.http.post('/api/v2/sport/editPrivacy', body).pipe(catchError((err) => throwError(err)))
    );
  }
}

const api2103Response = {
  alaFormatVersionName: '1.6.7',
  apiCode: 2103,
  msgCode: 1042,
  resultCode: 200,
  resultMessage: 'Get sport data detail success.',
  fileInfo: {
    author: 'Kidin_real?userId=384',
    branch: null,
    brand: 'Kidin(\u6e2c\u8a66)?groupId=0-0-102-0-0-0',
    class: 'Coding?groupId=0-0-102-1-1-0',
    company: '',
    complexId: null,
    countryRegion: 'TW',
    createFrom: 'ALA Train Live?appId=3',
    creationDate: '2022-09-16T07:51:40.872+08:00',
    creationTimeZone: '+08:00',
    creationUnixTimeStamp: '20220916075140',
    dispName: '複合式運動',
    editDate: '2022-09-16T07:51:40.872+08:00',
    equipmentFwName: null,
    equipmentFwCode: null,
    equipmentHwName: null,
    equipmentHwCode: null,
    equipmentSN: ['C05WB002010007', 'C05P1000000001', 'C05T0100000001', 'C05R7000000001'],
    exampleFormat: null,
    fileId: 6641,
    language: 'zh',
    location: null,
    note: null,
    photo: null,
    privacy: ['1', '3', '4', '99'],
    syncDate: '2022-10-12T17:13:47.589+08:00',
    tag: [],
    tagman: [],
    teacher: '\u2620\u96de\u4e01\u2623?userId=408',
    type: '2',
    uploadRawFileName: '9280bf8e121a6637724b00541288cffd',
    versionCode: null,
    versionName: '1.6.7',
    video: null,
  },
  activityInfoLayer: {
    //複合式運動檔案之檔頭資訊activityInfo
    avgHeartRateBpm: 93,
    avgSpeed: 8.34366,
    calories: 15.0,
    maxHeartRateBpm: 99,
    maxSpeed: 15,
    startTime: '2022-09-16T20:51:36.000+08:00',
    totalDistanceMeters: 501.0,
    totalSecond: 216,
    type: '100',
    subtype: 0,
    totalHrZone0Second: 75,
    totalHrZone1Second: 0,
    totalHrZone2Second: 0,
    totalHrZone3Second: 0,
    totalHrZone4Second: 0,
    totalHrZone5Second: 0,
  },
  info: [
    {
      fileInfo: {
        type: '2',
        fileId: 26912,
        creationDate: '2022-11-01T16:51:23.000+08:00',
        creationUnixTimeStamp: null,
        creationTimeZone: '+08:00',
        createFrom: 'Android-2.1.1.2?appId=1',
        countryRegion: 'TW',
        language: 'zh',
        complexId: null,
        syncDate: '2022-11-01T16:55:39.000+08:00',
        author: 'Kidin_real?userId=384',
        editDate: null,
        exampleFormat: null,
        versionName: '1.6.5',
        versionCode: '0',
        location: null,
        photo: null,
        video: null,
        tag: [],
        tagman: [],
        note: null,
        privacy: ['99'],
        teacher: null,
        class: null,
        brand: null,
        company: null,
        dispName: '\u6e38\u6cf3',
        equipmentSN: ['C29WB002010119'],
        equipmentFwName: '0.0.1',
        equipmentFwCode: '138',
        equipmentHwName: '0',
        equipmentHwCode: '20',
        branch: null,
        uploadRawFileName: 'fe093054b4a7f70449c97eab82199ec8',
        fileGroupId: null,
        cloudRunMapId: null,
        matchedPlanId: null,
      },
      activityInfoLayer: {
        type: '4',
        resolutionSeconds: 1,
        startTime: '2022-11-01T16:51:23.000+08:00',
        pluginBluetoothSensorName: [],
        pluginAntSensorName: [],
        totalPoint: 77,
        totalLapOrSet: 3,
        totalActivityLapOrSet: 3,
        totalRestLapOrSet: 0,
        totalSecond: 76,
        totalActivitySecond: 51,
        totalRestSecond: 0,
        totalDistanceMeters: 50.0,
        avgHeartRateBpm: 78,
        maxHeartRateBpm: 80,
        avgSpeed: 2.3,
        maxSpeed: 5.2,
        calories: 0.0,
        swimAvgCadence: 32,
        swimMaxCadence: 43,
        totalStrokes: 10,
        poolLengthMeters: 25,
        poolSwimAvgCadence: 5,
        mets: null,
        avgTemp: 27.0,
        maxTemp: 27.0,
        minTemp: 27.0,
        avgMoveSpeed: 3.4,
        gpsSensorStatus: '0',
        ohrSensorStatus: '1',
        gravitySensorStatus: '1',
        tempSensorStatus: '1',
        atmSensorStatus: '0',
        gyroSensorStatus: '1',
        complexActivity: null,
        avgSwolf: null,
        bestSwolf: null,
        totalHrZone0Second: 75,
        totalHrZone1Second: 0,
        totalHrZone2Second: 0,
        totalHrZone3Second: 0,
        totalHrZone4Second: 0,
        totalHrZone5Second: 0,
        resolutionMillisecondStatus: 0,
        subtype: 1,
        personalizedActivityIntelligence: null,
      },
      activityLapLayer: [
        {
          type: '0',
          dispName: 'ERROR',
          lapStartTime: null,
          lapStartSecondPoint: 0,
          lapTotalSecond: '31',
          lapTotalDistanceMeters: 25.0,
          lapAvgHeartRateBpm: 80.0,
          lapAvgSpeed: 5.2,
          lapSwimAvgCadence: 43.0,
          lapTotalStrokes: 6,
          lapSwimPosture: '3',
          lapIndex: 1,
          lapSwolf: null,
        },
        {
          type: '0',
          dispName: 'ERROR',
          lapStartTime: null,
          lapStartSecondPoint: 31,
          lapTotalSecond: '45',
          lapTotalDistanceMeters: 25.0,
          lapAvgHeartRateBpm: 78.0,
          lapAvgSpeed: 3.8,
          lapSwimAvgCadence: 31.0,
          lapTotalStrokes: 4,
          lapSwimPosture: '3',
          lapIndex: 2,
          lapSwolf: null,
        },
      ],
      activityPointLayer: [
        {
          pointSecond: 1,
          distanceMeters: '0.0',
          heartRateBpm: 0.0,
          speed: 0.0,
          swimCadence: 0.0,
          swimPosture: '1',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 2,
          distanceMeters: '0.0',
          heartRateBpm: 0.0,
          speed: 0.0,
          swimCadence: 0.0,
          swimPosture: '1',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 3,
          distanceMeters: '0.0',
          heartRateBpm: 0.0,
          speed: 0.0,
          swimCadence: 0.0,
          swimPosture: '1',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 4,
          distanceMeters: '0.0',
          heartRateBpm: 0.0,
          speed: 0.0,
          swimCadence: 0.0,
          swimPosture: '1',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 5,
          distanceMeters: '0.0',
          heartRateBpm: 0.0,
          speed: 0.0,
          swimCadence: 0.0,
          swimPosture: '1',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 6,
          distanceMeters: '0.0',
          heartRateBpm: 0.0,
          speed: 0.0,
          swimCadence: 0.0,
          swimPosture: '1',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 7,
          distanceMeters: '0.0',
          heartRateBpm: 0.0,
          speed: 0.0,
          swimCadence: 0.0,
          swimPosture: '1',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 8,
          distanceMeters: '0.0',
          heartRateBpm: 0.0,
          speed: 0.0,
          swimCadence: 0.0,
          swimPosture: '1',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 9,
          distanceMeters: '0.0',
          heartRateBpm: 0.0,
          speed: 0.0,
          swimCadence: 0.0,
          swimPosture: '1',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 10,
          distanceMeters: '0.0',
          heartRateBpm: 0.0,
          speed: 0.0,
          swimCadence: 0.0,
          swimPosture: '1',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 11,
          distanceMeters: '0.0',
          heartRateBpm: 0.0,
          speed: 0.0,
          swimCadence: 0.0,
          swimPosture: '1',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 12,
          distanceMeters: '0.0',
          heartRateBpm: 0.0,
          speed: 0.0,
          swimCadence: 0.0,
          swimPosture: '1',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 13,
          distanceMeters: '0.0',
          heartRateBpm: 0.0,
          speed: 0.0,
          swimCadence: 0.0,
          swimPosture: '1',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 14,
          distanceMeters: '0.0',
          heartRateBpm: 0.0,
          speed: 0.0,
          swimCadence: 0.0,
          swimPosture: '1',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 15,
          distanceMeters: '0.0',
          heartRateBpm: 0.0,
          speed: 0.0,
          swimCadence: 0.0,
          swimPosture: '1',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 16,
          distanceMeters: '0.0',
          heartRateBpm: 0.0,
          speed: 0.0,
          swimCadence: 0.0,
          swimPosture: '1',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 17,
          distanceMeters: '0.0',
          heartRateBpm: 0.0,
          speed: 0.0,
          swimCadence: 0.0,
          swimPosture: '1',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 18,
          distanceMeters: '0.0',
          heartRateBpm: 0.0,
          speed: 0.0,
          swimCadence: 0.0,
          swimPosture: '1',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 19,
          distanceMeters: '0.0',
          heartRateBpm: 0.0,
          speed: 0.0,
          swimCadence: 0.0,
          swimPosture: '1',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 20,
          distanceMeters: '0.0',
          heartRateBpm: 0.0,
          speed: 0.0,
          swimCadence: 0.0,
          swimPosture: '1',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 21,
          distanceMeters: '0.0',
          heartRateBpm: 0.0,
          speed: 0.0,
          swimCadence: 0.0,
          swimPosture: '1',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 22,
          distanceMeters: '0.0',
          heartRateBpm: 0.0,
          speed: 0.0,
          swimCadence: 0.0,
          swimPosture: '1',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 23,
          distanceMeters: '0.0',
          heartRateBpm: 0.0,
          speed: 0.0,
          swimCadence: 0.0,
          swimPosture: '1',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 24,
          distanceMeters: '0.0',
          heartRateBpm: 0.0,
          speed: 0.0,
          swimCadence: 0.0,
          swimPosture: '1',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 25,
          distanceMeters: '0.0',
          heartRateBpm: 0.0,
          speed: 0.0,
          swimCadence: 0.0,
          swimPosture: '1',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 26,
          distanceMeters: '0.0',
          heartRateBpm: 0.0,
          speed: 5.2,
          swimCadence: 43.0,
          swimPosture: '2',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 27,
          distanceMeters: '0.0',
          heartRateBpm: 0.0,
          speed: 5.2,
          swimCadence: 43.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 28,
          distanceMeters: '0.0',
          heartRateBpm: 0.0,
          speed: 5.2,
          swimCadence: 43.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 29,
          distanceMeters: '0.0',
          heartRateBpm: 80.0,
          speed: 5.2,
          swimCadence: 43.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 30,
          distanceMeters: '0.0',
          heartRateBpm: 80.0,
          speed: 5.2,
          swimCadence: 43.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 31,
          distanceMeters: '25.0',
          heartRateBpm: 80.0,
          speed: 5.2,
          swimCadence: 43.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 32,
          distanceMeters: '25.0',
          heartRateBpm: 79.0,
          speed: 5.2,
          swimCadence: 43.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 33,
          distanceMeters: '25.0',
          heartRateBpm: 77.0,
          speed: 5.2,
          swimCadence: 43.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 34,
          distanceMeters: '25.0',
          heartRateBpm: 77.0,
          speed: 5.2,
          swimCadence: 43.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 35,
          distanceMeters: '25.0',
          heartRateBpm: 76.0,
          speed: 5.2,
          swimCadence: 43.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 36,
          distanceMeters: '25.0',
          heartRateBpm: 77.0,
          speed: 5.2,
          swimCadence: 43.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 37,
          distanceMeters: '25.0',
          heartRateBpm: 76.0,
          speed: 5.2,
          swimCadence: 43.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 38,
          distanceMeters: '25.0',
          heartRateBpm: 77.0,
          speed: 5.2,
          swimCadence: 43.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 39,
          distanceMeters: '25.0',
          heartRateBpm: 77.0,
          speed: 5.2,
          swimCadence: 43.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 40,
          distanceMeters: '25.0',
          heartRateBpm: 75.0,
          speed: 5.2,
          swimCadence: 43.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 41,
          distanceMeters: '25.0',
          heartRateBpm: 77.0,
          speed: 5.2,
          swimCadence: 43.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 42,
          distanceMeters: '25.0',
          heartRateBpm: 77.0,
          speed: 5.2,
          swimCadence: 43.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 43,
          distanceMeters: '25.0',
          heartRateBpm: 77.0,
          speed: 5.2,
          swimCadence: 43.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 44,
          distanceMeters: '25.0',
          heartRateBpm: 77.0,
          speed: 5.2,
          swimCadence: 43.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 45,
          distanceMeters: '25.0',
          heartRateBpm: 77.0,
          speed: 3.3,
          swimCadence: 27.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 46,
          distanceMeters: '25.0',
          heartRateBpm: 77.0,
          speed: 3.3,
          swimCadence: 27.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 47,
          distanceMeters: '25.0',
          heartRateBpm: 79.0,
          speed: 3.3,
          swimCadence: 27.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 48,
          distanceMeters: '25.0',
          heartRateBpm: 80.0,
          speed: 3.3,
          swimCadence: 27.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 49,
          distanceMeters: '25.0',
          heartRateBpm: 80.0,
          speed: 3.3,
          swimCadence: 27.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 50,
          distanceMeters: '25.0',
          heartRateBpm: 79.0,
          speed: 3.3,
          swimCadence: 27.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 51,
          distanceMeters: '25.0',
          heartRateBpm: 80.0,
          speed: 3.3,
          swimCadence: 27.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 52,
          distanceMeters: '25.0',
          heartRateBpm: 80.0,
          speed: 3.3,
          swimCadence: 27.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 53,
          distanceMeters: '25.0',
          heartRateBpm: 80.0,
          speed: 3.3,
          swimCadence: 27.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 54,
          distanceMeters: '25.0',
          heartRateBpm: 80.0,
          speed: 3.3,
          swimCadence: 27.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 55,
          distanceMeters: '25.0',
          heartRateBpm: 80.0,
          speed: 3.3,
          swimCadence: 27.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 56,
          distanceMeters: '25.0',
          heartRateBpm: 80.0,
          speed: 3.3,
          swimCadence: 27.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 57,
          distanceMeters: '25.0',
          heartRateBpm: 80.0,
          speed: 3.3,
          swimCadence: 27.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 58,
          distanceMeters: '25.0',
          heartRateBpm: 80.0,
          speed: 3.3,
          swimCadence: 27.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 59,
          distanceMeters: '25.0',
          heartRateBpm: 79.0,
          speed: 3.3,
          swimCadence: 27.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 60,
          distanceMeters: '25.0',
          heartRateBpm: 79.0,
          speed: 3.3,
          swimCadence: 27.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 61,
          distanceMeters: '25.0',
          heartRateBpm: 79.0,
          speed: 3.3,
          swimCadence: 27.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 62,
          distanceMeters: '25.0',
          heartRateBpm: 79.0,
          speed: 3.3,
          swimCadence: 27.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 63,
          distanceMeters: '25.0',
          heartRateBpm: 79.0,
          speed: 3.3,
          swimCadence: 27.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 64,
          distanceMeters: '25.0',
          heartRateBpm: 79.0,
          speed: 3.3,
          swimCadence: 27.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 65,
          distanceMeters: '25.0',
          heartRateBpm: 79.0,
          speed: 3.3,
          swimCadence: 27.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 66,
          distanceMeters: '25.0',
          heartRateBpm: 79.0,
          speed: 3.3,
          swimCadence: 27.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 67,
          distanceMeters: '25.0',
          heartRateBpm: 79.0,
          speed: 3.3,
          swimCadence: 27.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 68,
          distanceMeters: '25.0',
          heartRateBpm: 79.0,
          speed: 3.3,
          swimCadence: 27.0,
          swimPosture: '2',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 69,
          distanceMeters: '25.0',
          heartRateBpm: 79.0,
          speed: 3.3,
          swimCadence: 27.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 70,
          distanceMeters: '25.0',
          heartRateBpm: 78.0,
          speed: 3.3,
          swimCadence: 27.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 71,
          distanceMeters: '25.0',
          heartRateBpm: 78.0,
          speed: 3.3,
          swimCadence: 27.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 72,
          distanceMeters: '25.0',
          heartRateBpm: 78.0,
          speed: 3.3,
          swimCadence: 27.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 73,
          distanceMeters: '25.0',
          heartRateBpm: 79.0,
          speed: 3.3,
          swimCadence: 27.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 74,
          distanceMeters: '25.0',
          heartRateBpm: 78.0,
          speed: 3.3,
          swimCadence: 27.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 75,
          distanceMeters: '25.0',
          heartRateBpm: 78.0,
          speed: 3.3,
          swimCadence: 27.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 76,
          distanceMeters: '25.0',
          heartRateBpm: 80.0,
          speed: 3.3,
          swimCadence: 27.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 76,
          distanceMeters: '25.0',
          heartRateBpm: 80.0,
          speed: 3.3,
          swimCadence: 27.0,
          swimPosture: '3',
          temp: 27.0,
          equipmentResistanceWeightsKg: null,
          levelOfDifficulty: null,
        },
      ],
    },
    {
      activityInfoLayer: {
        atmSensorStatus: 0,
        avgHeartRateBpm: 99,
        avgTemp: null,
        calories: 403,
        gpsSensorStatus: 0,
        gravitySensorStatus: 0,
        gyroSensorStatus: 0,
        maxHeartRateBpm: 128,
        maxTemp: null,
        minTemp: null,
        ohrSensorStatus: 1,
        pluginAntSensorName: [],
        pluginBluetoothSensorName: [],
        resolutionSeconds: 3,
        startTime: '2022-09-16T19:37:27.000+08:00',
        tempSensorStatus: 1,
        totalActivityLapOrSet: 1,
        totalActivitySecond: 4449,
        totalLapOrSet: 0,
        totalPoint: 1484,
        totalRestLapOrSet: 0,
        totalRestSecond: 0,
        totalSecond: 4449,
        type: '101',
        totalHrZone0Second: 15,
        totalHrZone1Second: 0,
        totalHrZone2Second: 0,
        totalHrZone3Second: 0,
        totalHrZone4Second: 0,
        totalHrZone5Second: 0,
      },
      activityLapLayer: [
        {
          dispName: '',
          lapAvgHeartRateBpm: 99,
          lapIndex: 1,
          lapStartSecondPoint: 0,
          lapTotalSecond: '4449',
          type: '0',
        },
      ],
      activityPointLayer: [
        {
          heartRateBpm: 71,
          pointSecond: 3,
          temp: 0,
        },
        {
          heartRateBpm: 101,
          pointSecond: 6,
          temp: 0,
        },
      ],
      fileInfo: {
        type: '2',
        fileId: 26912,
        creationDate: '2022-11-01T16:51:23.000+08:00',
        creationUnixTimeStamp: null,
        creationTimeZone: '+08:00',
        createFrom: 'Android-2.1.1.2?appId=1',
        countryRegion: 'TW',
        language: 'zh',
        complexId: null,
        syncDate: '2022-11-01T16:55:39.000+08:00',
        author: 'Kidin_real?userId=384',
        editDate: null,
        exampleFormat: null,
        versionName: '1.6.5',
        versionCode: '0',
        location: null,
        photo: null,
        video: null,
        tag: [],
        tagman: [],
        note: null,
        privacy: ['99'],
        teacher: null,
        class: null,
        brand: null,
        company: null,
        dispName: '\u6e38\u6cf3',
        equipmentSN: ['C29WB002010119'],
        equipmentFwName: '0.0.1',
        equipmentFwCode: '138',
        equipmentHwName: '0',
        equipmentHwCode: '20',
        branch: null,
        uploadRawFileName: 'fe093054b4a7f70449c97eab82199ec8',
        fileGroupId: null,
        cloudRunMapId: null,
        matchedPlanId: null,
      },
    },
    {
      fileInfo: {
        type: '2',
        fileId: 26765,
        creationDate: '2022-09-14T10:31:36.572+08:00',
        creationUnixTimeStamp: '1663122696573',
        creationTimeZone: '+08:00',
        createFrom: 'Ala Fitness?appId=4',
        countryRegion: 'TW',
        language: 'zh',
        complexId: null,
        syncDate: '2022-09-14T10:31:36.572+08:00',
        author: 'Kidin_real?userId=384',
        editDate: '2022-09-14T10:31:36.572+08:00',
        exampleFormat: null,
        versionName: '1.6.3',
        versionCode: '1',
        location: null,
        photo: '',
        video: null,
        tag: [],
        tagman: [],
        note: null,
        privacy: ['1', '3', '4', '99'],
        teacher: null,
        class: null,
        brand: null,
        company: null,
        dispName: '\u6709\u6c27\u904b\u52d5',
        equipmentSN: ['C29WB002010119'],
        equipmentFwName: null,
        equipmentFwCode: null,
        equipmentHwName: null,
        equipmentHwCode: null,
        branch: null,
        uploadRawFileName: '418cb6e038e90cb09085a38b25ccc2de',
        fileGroupId: null,
        cloudRunMapId: null,
        matchedPlanId: null,
      },
      activityInfoLayer: {
        type: '5',
        resolutionSeconds: 3,
        startTime: '2022-09-14T10:30:48.590+08:00',
        pluginBluetoothSensorName: ['C29WB002010119'],
        pluginAntSensorName: [],
        totalPoint: 11,
        totalLapOrSet: 2,
        totalActivityLapOrSet: 2,
        totalRestLapOrSet: 0,
        totalSecond: 32,
        totalActivitySecond: 32,
        totalRestSecond: 0,
        calories: 2.03203,
        avgHeartRateBpm: 103,
        maxHeartRateBpm: 109,
        mets: null,
        avgTemp: null,
        maxTemp: null,
        minTemp: null,
        avgMoveSpeed: null,
        gpsSensorStatus: null,
        ohrSensorStatus: null,
        gravitySensorStatus: null,
        tempSensorStatus: null,
        atmSensorStatus: null,
        gyroSensorStatus: null,
        complexActivity: null,
        totalHrZone0Second: 0,
        totalHrZone1Second: 32,
        totalHrZone2Second: 0,
        totalHrZone3Second: 0,
        totalHrZone4Second: 0,
        totalHrZone5Second: 0,
        resolutionMillisecondStatus: 0,
        subtype: 0,
        personalizedActivityIntelligence: null,
      },
      activityLapLayer: [
        {
          type: '0',
          dispName: '',
          lapStartSecondPoint: 1,
          lapTotalSecond: '30',
          lapAvgHeartRateBpm: 103.0,
          lapIndex: 1,
        },
        {
          type: '0',
          dispName: '',
          lapStartSecondPoint: 11,
          lapTotalSecond: '2',
          lapAvgHeartRateBpm: 107.0,
          lapIndex: 2,
        },
      ],
      activityPointLayer: [
        {
          pointSecond: 2,
          heartRateBpm: 99.0,
          temp: null,
          equipmentResistanceWeightsKg: null,
          equipmentIncline: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 5,
          heartRateBpm: 99.0,
          temp: null,
          equipmentResistanceWeightsKg: null,
          equipmentIncline: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 8,
          heartRateBpm: 99.0,
          temp: null,
          equipmentResistanceWeightsKg: null,
          equipmentIncline: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 11,
          heartRateBpm: 99.0,
          temp: null,
          equipmentResistanceWeightsKg: null,
          equipmentIncline: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 14,
          heartRateBpm: 102.0,
          temp: null,
          equipmentResistanceWeightsKg: null,
          equipmentIncline: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 17,
          heartRateBpm: 108.0,
          temp: null,
          equipmentResistanceWeightsKg: null,
          equipmentIncline: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 20,
          heartRateBpm: 108.0,
          temp: null,
          equipmentResistanceWeightsKg: null,
          equipmentIncline: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 23,
          heartRateBpm: 106.0,
          temp: null,
          equipmentResistanceWeightsKg: null,
          equipmentIncline: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 26,
          heartRateBpm: 105.0,
          temp: null,
          equipmentResistanceWeightsKg: null,
          equipmentIncline: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 29,
          heartRateBpm: 106.0,
          temp: null,
          equipmentResistanceWeightsKg: null,
          equipmentIncline: null,
          levelOfDifficulty: null,
        },
        {
          pointSecond: 32,
          heartRateBpm: 109.0,
          temp: null,
          equipmentResistanceWeightsKg: null,
          equipmentIncline: null,
          levelOfDifficulty: null,
        },
      ],
    },
    {
      activityInfoLayer: {
        atmSensorStatus: 0,
        avgHeartRateBpm: 99,
        avgTemp: null,
        calories: 403,
        gpsSensorStatus: 0,
        gravitySensorStatus: 0,
        gyroSensorStatus: 0,
        maxHeartRateBpm: 128,
        maxTemp: null,
        minTemp: null,
        ohrSensorStatus: 1,
        pluginAntSensorName: [],
        pluginBluetoothSensorName: [],
        resolutionSeconds: 3,
        startTime: '2022-09-16T19:37:27.000+08:00',
        tempSensorStatus: 1,
        totalActivityLapOrSet: 1,
        totalActivitySecond: 4449,
        totalLapOrSet: 0,
        totalPoint: 1484,
        totalRestLapOrSet: 0,
        totalRestSecond: 0,
        totalSecond: 4449,
        type: '101',
        totalHrZone0Second: 15,
        totalHrZone1Second: 0,
        totalHrZone2Second: 0,
        totalHrZone3Second: 0,
        totalHrZone4Second: 0,
        totalHrZone5Second: 0,
      },
      activityLapLayer: [
        {
          dispName: '',
          lapAvgHeartRateBpm: 99,
          lapIndex: 1,
          lapStartSecondPoint: 0,
          lapTotalSecond: '4449',
          type: '0',
        },
      ],
      activityPointLayer: [
        {
          heartRateBpm: 71,
          pointSecond: 3,
          temp: 0,
        },
        {
          heartRateBpm: 101,
          pointSecond: 6,
          temp: 0,
        },
      ],
      fileInfo: {
        author: "vincent_shih's?userId=1",
        branch: 20,
        brand: '',
        class: '',
        company: '',
        countryRegion: 'TW',
        createFrom: 'iOS Connect BETA:4',
        creationDate: '2022-09-16T19:38:38.000+08:00',
        creationTimeZone: '+08:00',
        creationUnixTimeStamp: '',
        dispName: '休息轉換',
        editDate: '2022-09-16T19:38:38.000+08:00',
        equipmentFwCode: '0.0.1',
        equipmentFwName: '',
        equipmentHwCode: 0,
        equipmentHwName: 62,
        equipmentSN: ['C05WB002010007'],
        exampleFormat: '',
        fileId: 6640,
        language: 'zh',
        location: 0,
        note: '',
        photo: '',
        privacy: ['1'],
        syncDate: '2022-09-16T19:38:38.000+08:00',
        tag: '',
        tagman: '',
        teacher: '',
        type: 2,
        uploadRawFileName: '',
        versionCode: '1.5.7',
        versionName: '',
        video: '',
      },
    },
    {
      fileInfo: {
        type: '2',
        fileId: 26764,
        creationDate: '2022-09-14T10:30:19.458+08:00',
        creationUnixTimeStamp: '1663122619461',
        creationTimeZone: '+08:00',
        createFrom: 'Ala Fitness?appId=4',
        countryRegion: 'TW',
        language: 'zh',
        complexId: null,
        syncDate: '2022-09-14T10:30:19.458+08:00',
        author: 'Kidin_real?userId=384',
        editDate: '2022-09-14T10:30:19.458+08:00',
        exampleFormat: null,
        versionName: '1.6.3',
        versionCode: '1',
        location: null,
        photo: '',
        video: null,
        tag: [],
        tagman: [],
        note: null,
        privacy: ['1', '3', '4', '99'],
        teacher: null,
        class: null,
        brand: null,
        company: null,
        dispName: 'South District \u81ea\u884c\u8eca',
        equipmentSN: ['C29WB002010119'],
        equipmentFwName: null,
        equipmentFwCode: null,
        equipmentHwName: null,
        equipmentHwCode: null,
        branch: null,
        uploadRawFileName: '3aa530de6630ef5a2b421d1daf627c70',
        fileGroupId: null,
        cloudRunMapId: null,
        matchedPlanId: null,
      },
      activityInfoLayer: {
        type: '2',
        resolutionSeconds: 3,
        startTime: '2022-09-14T10:28:46.536+08:00',
        pluginBluetoothSensorName: ['C29WB002010119'],
        pluginAntSensorName: [],
        totalPoint: 25,
        totalLapOrSet: 1,
        totalActivityLapOrSet: 1,
        totalRestLapOrSet: 0,
        totalSecond: 74,
        totalActivitySecond: 74,
        totalRestSecond: 0,
        totalDistanceMeters: 0.0,
        elevGain: 0.0,
        elevLoss: 0.0,
        maxElev: 0.0,
        minElev: 0.0,
        avgElevGainSpeed: 0.0,
        maxElevGainSpeed: null,
        avgElevLossSpeed: 0.0,
        maxElevLossSpeed: null,
        avgHeartRateBpm: 127,
        maxHeartRateBpm: 135,
        avgSpeed: 0.0,
        maxSpeed: 2.4,
        calories: 9.53413,
        cycleAvgCadence: 0,
        cycleMaxCadence: 0,
        cycleWheelDiameter: 2000,
        totalRevolution: 0,
        cycleAvgWatt: null,
        cycleMaxWatt: null,
        mets: null,
        avgTemp: null,
        maxTemp: null,
        minTemp: null,
        avgMoveSpeed: 0.0,
        gpsSensorStatus: '1',
        ohrSensorStatus: null,
        gravitySensorStatus: null,
        tempSensorStatus: null,
        atmSensorStatus: null,
        gyroSensorStatus: null,
        complexActivity: null,
        avgClimbInclineRatio: null,
        max100mInclineRatio: null,
        min100mInclineRatio: null,
        totalHrZone0Second: 0,
        totalHrZone1Second: 0,
        totalHrZone2Second: 63,
        totalHrZone3Second: 11,
        totalHrZone4Second: 0,
        totalHrZone5Second: 0,
        totalElevGainSecond: 0,
        totalElevLossSecond: 0,
        resolutionMillisecondStatus: 0,
        totalFtpZone0Second: null,
        totalFtpZone1Second: null,
        totalFtpZone2Second: null,
        totalFtpZone3Second: null,
        totalFtpZone4Second: null,
        totalFtpZone5Second: null,
        totalFtpZone6Second: null,
        subtype: 0,
        estimateFtp: null,
        personalizedActivityIntelligence: null,
        totalFeedbackEnergy: null,
      },
      activityLapLayer: [
        {
          type: '0',
          dispName: '',
          lapStartTime: null,
          lapStartSecondPoint: 1,
          lapTotalSecond: '74',
          lapTotalDistanceMeters: 0.7,
          lapAvgHeartRateBpm: 127.0,
          lapAvgSpeed: 0.0,
          lapCycleAvgCadence: 0.0,
          lapElevGainSpeed: null,
          lapElevLossSpeed: null,
          lapCycleAvgWatt: null,
          lapCycleAvgWattLeft: null,
          lapCycleAvgWattRight: null,
          lapElevGain: 0.0,
          lapElevLoss: 0.0,
          lapIndex: 1,
          lapAvgClimbInclineRatio: null,
          feedbackEnergy: null,
        },
      ],
      activityPointLayer: [
        {
          pointSecond: 2,
          latitudeDegrees: '24.1237833',
          longitudeDegrees: '120.6605986',
          altitudeMeters: '192.8',
          distanceMeters: '0.7',
          elevGainMeters: 0.0,
          elevLossMeters: 0.0,
          heartRateBpm: 126.0,
          speed: 2.4,
          elevGainSpeed: null,
          elevLossSpeed: null,
          cycleCadence: 0.0,
          cycleWatt: 0.0,
          cycleWattLeft: null,
          cycleWattRight: null,
          temp: null,
          equipmentResistanceWeightsKg: null,
          equipmentIncline: null,
          localPressure: null,
          seaLevelPressure: null,
          gpsHorizontalAccuracyMeter: null,
          gpsVerticalAccuracyMeter: null,
          satellitesSignalStrength: [],
          altimeterRawMeter: null,
          levelOfDifficulty: null,
          feedbackWatt: null,
        },
        {
          pointSecond: 5,
          latitudeDegrees: '24.1237881',
          longitudeDegrees: '120.660593',
          altitudeMeters: '192.8',
          distanceMeters: '0.7',
          elevGainMeters: 0.0,
          elevLossMeters: 0.0,
          heartRateBpm: 126.0,
          speed: 0.0,
          elevGainSpeed: null,
          elevLossSpeed: null,
          cycleCadence: 0.0,
          cycleWatt: 0.0,
          cycleWattLeft: null,
          cycleWattRight: null,
          temp: null,
          equipmentResistanceWeightsKg: null,
          equipmentIncline: null,
          localPressure: null,
          seaLevelPressure: null,
          gpsHorizontalAccuracyMeter: null,
          gpsVerticalAccuracyMeter: null,
          satellitesSignalStrength: [],
          altimeterRawMeter: null,
          levelOfDifficulty: null,
          feedbackWatt: null,
        },
        {
          pointSecond: 8,
          latitudeDegrees: '24.123789',
          longitudeDegrees: '120.6605949',
          altitudeMeters: '192.8',
          distanceMeters: '0.7',
          elevGainMeters: 0.0,
          elevLossMeters: 0.0,
          heartRateBpm: 130.0,
          speed: 0.0,
          elevGainSpeed: null,
          elevLossSpeed: null,
          cycleCadence: 0.0,
          cycleWatt: 0.0,
          cycleWattLeft: null,
          cycleWattRight: null,
          temp: null,
          equipmentResistanceWeightsKg: null,
          equipmentIncline: null,
          localPressure: null,
          seaLevelPressure: null,
          gpsHorizontalAccuracyMeter: null,
          gpsVerticalAccuracyMeter: null,
          satellitesSignalStrength: [],
          altimeterRawMeter: null,
          levelOfDifficulty: null,
          feedbackWatt: null,
        },
        {
          pointSecond: 11,
          latitudeDegrees: '24.1237915',
          longitudeDegrees: '120.6605954',
          altitudeMeters: '192.8',
          distanceMeters: '0.7',
          elevGainMeters: 0.0,
          elevLossMeters: 0.0,
          heartRateBpm: 130.0,
          speed: 0.0,
          elevGainSpeed: null,
          elevLossSpeed: null,
          cycleCadence: 0.0,
          cycleWatt: 0.0,
          cycleWattLeft: null,
          cycleWattRight: null,
          temp: null,
          equipmentResistanceWeightsKg: null,
          equipmentIncline: null,
          localPressure: null,
          seaLevelPressure: null,
          gpsHorizontalAccuracyMeter: null,
          gpsVerticalAccuracyMeter: null,
          satellitesSignalStrength: [],
          altimeterRawMeter: null,
          levelOfDifficulty: null,
          feedbackWatt: null,
        },
        {
          pointSecond: 14,
          latitudeDegrees: '24.1237934',
          longitudeDegrees: '120.6605967',
          altitudeMeters: '192.8',
          distanceMeters: '0.7',
          elevGainMeters: 0.0,
          elevLossMeters: 0.0,
          heartRateBpm: 129.0,
          speed: 0.0,
          elevGainSpeed: null,
          elevLossSpeed: null,
          cycleCadence: 0.0,
          cycleWatt: 0.0,
          cycleWattLeft: null,
          cycleWattRight: null,
          temp: null,
          equipmentResistanceWeightsKg: null,
          equipmentIncline: null,
          localPressure: null,
          seaLevelPressure: null,
          gpsHorizontalAccuracyMeter: null,
          gpsVerticalAccuracyMeter: null,
          satellitesSignalStrength: [],
          altimeterRawMeter: null,
          levelOfDifficulty: null,
          feedbackWatt: null,
        },
        {
          pointSecond: 17,
          latitudeDegrees: '24.1237933',
          longitudeDegrees: '120.6605954',
          altitudeMeters: '192.8',
          distanceMeters: '0.7',
          elevGainMeters: 0.0,
          elevLossMeters: 0.0,
          heartRateBpm: 128.0,
          speed: 0.0,
          elevGainSpeed: null,
          elevLossSpeed: null,
          cycleCadence: 0.0,
          cycleWatt: 0.0,
          cycleWattLeft: null,
          cycleWattRight: null,
          temp: null,
          equipmentResistanceWeightsKg: null,
          equipmentIncline: null,
          localPressure: null,
          seaLevelPressure: null,
          gpsHorizontalAccuracyMeter: null,
          gpsVerticalAccuracyMeter: null,
          satellitesSignalStrength: [],
          altimeterRawMeter: null,
          levelOfDifficulty: null,
          feedbackWatt: null,
        },
        {
          pointSecond: 20,
          latitudeDegrees: '24.123793',
          longitudeDegrees: '120.6605948',
          altitudeMeters: '192.8',
          distanceMeters: '0.7',
          elevGainMeters: 0.0,
          elevLossMeters: 0.0,
          heartRateBpm: 127.0,
          speed: 0.0,
          elevGainSpeed: null,
          elevLossSpeed: null,
          cycleCadence: 0.0,
          cycleWatt: 0.0,
          cycleWattLeft: null,
          cycleWattRight: null,
          temp: null,
          equipmentResistanceWeightsKg: null,
          equipmentIncline: null,
          localPressure: null,
          seaLevelPressure: null,
          gpsHorizontalAccuracyMeter: null,
          gpsVerticalAccuracyMeter: null,
          satellitesSignalStrength: [],
          altimeterRawMeter: null,
          levelOfDifficulty: null,
          feedbackWatt: null,
        },
        {
          pointSecond: 23,
          latitudeDegrees: '24.1237948',
          longitudeDegrees: '120.6605971',
          altitudeMeters: '192.8',
          distanceMeters: '0.7',
          elevGainMeters: 0.0,
          elevLossMeters: 0.0,
          heartRateBpm: 128.0,
          speed: 0.0,
          elevGainSpeed: null,
          elevLossSpeed: null,
          cycleCadence: 0.0,
          cycleWatt: 0.0,
          cycleWattLeft: null,
          cycleWattRight: null,
          temp: null,
          equipmentResistanceWeightsKg: null,
          equipmentIncline: null,
          localPressure: null,
          seaLevelPressure: null,
          gpsHorizontalAccuracyMeter: null,
          gpsVerticalAccuracyMeter: null,
          satellitesSignalStrength: [],
          altimeterRawMeter: null,
          levelOfDifficulty: null,
          feedbackWatt: null,
        },
        {
          pointSecond: 26,
          latitudeDegrees: '24.1237972',
          longitudeDegrees: '120.6605994',
          altitudeMeters: '192.8',
          distanceMeters: '0.7',
          elevGainMeters: 0.0,
          elevLossMeters: 0.0,
          heartRateBpm: 127.0,
          speed: 0.0,
          elevGainSpeed: null,
          elevLossSpeed: null,
          cycleCadence: 0.0,
          cycleWatt: 0.0,
          cycleWattLeft: null,
          cycleWattRight: null,
          temp: null,
          equipmentResistanceWeightsKg: null,
          equipmentIncline: null,
          localPressure: null,
          seaLevelPressure: null,
          gpsHorizontalAccuracyMeter: null,
          gpsVerticalAccuracyMeter: null,
          satellitesSignalStrength: [],
          altimeterRawMeter: null,
          levelOfDifficulty: null,
          feedbackWatt: null,
        },
        {
          pointSecond: 29,
          latitudeDegrees: '24.1237985',
          longitudeDegrees: '120.660601',
          altitudeMeters: '192.8',
          distanceMeters: '0.7',
          elevGainMeters: 0.0,
          elevLossMeters: 0.0,
          heartRateBpm: 128.0,
          speed: 0.0,
          elevGainSpeed: null,
          elevLossSpeed: null,
          cycleCadence: 0.0,
          cycleWatt: 0.0,
          cycleWattLeft: null,
          cycleWattRight: null,
          temp: null,
          equipmentResistanceWeightsKg: null,
          equipmentIncline: null,
          localPressure: null,
          seaLevelPressure: null,
          gpsHorizontalAccuracyMeter: null,
          gpsVerticalAccuracyMeter: null,
          satellitesSignalStrength: [],
          altimeterRawMeter: null,
          levelOfDifficulty: null,
          feedbackWatt: null,
        },
        {
          pointSecond: 32,
          latitudeDegrees: '24.1237991',
          longitudeDegrees: '120.6606024',
          altitudeMeters: '192.8',
          distanceMeters: '0.7',
          elevGainMeters: 0.0,
          elevLossMeters: 0.0,
          heartRateBpm: 131.0,
          speed: 0.0,
          elevGainSpeed: null,
          elevLossSpeed: null,
          cycleCadence: 0.0,
          cycleWatt: 0.0,
          cycleWattLeft: null,
          cycleWattRight: null,
          temp: null,
          equipmentResistanceWeightsKg: null,
          equipmentIncline: null,
          localPressure: null,
          seaLevelPressure: null,
          gpsHorizontalAccuracyMeter: null,
          gpsVerticalAccuracyMeter: null,
          satellitesSignalStrength: [],
          altimeterRawMeter: null,
          levelOfDifficulty: null,
          feedbackWatt: null,
        },
        {
          pointSecond: 35,
          latitudeDegrees: '24.1237989',
          longitudeDegrees: '120.6606043',
          altitudeMeters: '192.8',
          distanceMeters: '0.7',
          elevGainMeters: 0.0,
          elevLossMeters: 0.0,
          heartRateBpm: 134.0,
          speed: 0.0,
          elevGainSpeed: null,
          elevLossSpeed: null,
          cycleCadence: 0.0,
          cycleWatt: 0.0,
          cycleWattLeft: null,
          cycleWattRight: null,
          temp: null,
          equipmentResistanceWeightsKg: null,
          equipmentIncline: null,
          localPressure: null,
          seaLevelPressure: null,
          gpsHorizontalAccuracyMeter: null,
          gpsVerticalAccuracyMeter: null,
          satellitesSignalStrength: [],
          altimeterRawMeter: null,
          levelOfDifficulty: null,
          feedbackWatt: null,
        },
        {
          pointSecond: 38,
          latitudeDegrees: '24.1237987',
          longitudeDegrees: '120.6606046',
          altitudeMeters: '192.8',
          distanceMeters: '0.7',
          elevGainMeters: 0.0,
          elevLossMeters: 0.0,
          heartRateBpm: 135.0,
          speed: 0.0,
          elevGainSpeed: null,
          elevLossSpeed: null,
          cycleCadence: 0.0,
          cycleWatt: 0.0,
          cycleWattLeft: null,
          cycleWattRight: null,
          temp: null,
          equipmentResistanceWeightsKg: null,
          equipmentIncline: null,
          localPressure: null,
          seaLevelPressure: null,
          gpsHorizontalAccuracyMeter: null,
          gpsVerticalAccuracyMeter: null,
          satellitesSignalStrength: [],
          altimeterRawMeter: null,
          levelOfDifficulty: null,
          feedbackWatt: null,
        },
        {
          pointSecond: 41,
          latitudeDegrees: '24.1237987',
          longitudeDegrees: '120.660605',
          altitudeMeters: '192.8',
          distanceMeters: '0.7',
          elevGainMeters: 0.0,
          elevLossMeters: 0.0,
          heartRateBpm: 134.0,
          speed: 0.0,
          elevGainSpeed: null,
          elevLossSpeed: null,
          cycleCadence: 0.0,
          cycleWatt: 0.0,
          cycleWattLeft: null,
          cycleWattRight: null,
          temp: null,
          equipmentResistanceWeightsKg: null,
          equipmentIncline: null,
          localPressure: null,
          seaLevelPressure: null,
          gpsHorizontalAccuracyMeter: null,
          gpsVerticalAccuracyMeter: null,
          satellitesSignalStrength: [],
          altimeterRawMeter: null,
          levelOfDifficulty: null,
          feedbackWatt: null,
        },
        {
          pointSecond: 44,
          latitudeDegrees: '24.1237988',
          longitudeDegrees: '120.6606053',
          altitudeMeters: '192.8',
          distanceMeters: '0.7',
          elevGainMeters: 0.0,
          elevLossMeters: 0.0,
          heartRateBpm: 131.0,
          speed: 0.0,
          elevGainSpeed: null,
          elevLossSpeed: null,
          cycleCadence: 0.0,
          cycleWatt: 0.0,
          cycleWattLeft: null,
          cycleWattRight: null,
          temp: null,
          equipmentResistanceWeightsKg: null,
          equipmentIncline: null,
          localPressure: null,
          seaLevelPressure: null,
          gpsHorizontalAccuracyMeter: null,
          gpsVerticalAccuracyMeter: null,
          satellitesSignalStrength: [],
          altimeterRawMeter: null,
          levelOfDifficulty: null,
          feedbackWatt: null,
        },
        {
          pointSecond: 47,
          latitudeDegrees: '24.1237989',
          longitudeDegrees: '120.6606057',
          altitudeMeters: '192.8',
          distanceMeters: '0.7',
          elevGainMeters: 0.0,
          elevLossMeters: 0.0,
          heartRateBpm: 129.0,
          speed: 0.0,
          elevGainSpeed: null,
          elevLossSpeed: null,
          cycleCadence: 0.0,
          cycleWatt: 0.0,
          cycleWattLeft: null,
          cycleWattRight: null,
          temp: null,
          equipmentResistanceWeightsKg: null,
          equipmentIncline: null,
          localPressure: null,
          seaLevelPressure: null,
          gpsHorizontalAccuracyMeter: null,
          gpsVerticalAccuracyMeter: null,
          satellitesSignalStrength: [],
          altimeterRawMeter: null,
          levelOfDifficulty: null,
          feedbackWatt: null,
        },
        {
          pointSecond: 50,
          latitudeDegrees: '24.123799',
          longitudeDegrees: '120.660606',
          altitudeMeters: '192.8',
          distanceMeters: '0.7',
          elevGainMeters: 0.0,
          elevLossMeters: 0.0,
          heartRateBpm: 130.0,
          speed: 0.0,
          elevGainSpeed: null,
          elevLossSpeed: null,
          cycleCadence: 0.0,
          cycleWatt: 0.0,
          cycleWattLeft: null,
          cycleWattRight: null,
          temp: null,
          equipmentResistanceWeightsKg: null,
          equipmentIncline: null,
          localPressure: null,
          seaLevelPressure: null,
          gpsHorizontalAccuracyMeter: null,
          gpsVerticalAccuracyMeter: null,
          satellitesSignalStrength: [],
          altimeterRawMeter: null,
          levelOfDifficulty: null,
          feedbackWatt: null,
        },
        {
          pointSecond: 53,
          latitudeDegrees: '24.1237987',
          longitudeDegrees: '120.6606063',
          altitudeMeters: '192.8',
          distanceMeters: '0.7',
          elevGainMeters: 0.0,
          elevLossMeters: 0.0,
          heartRateBpm: 129.0,
          speed: 0.0,
          elevGainSpeed: null,
          elevLossSpeed: null,
          cycleCadence: 0.0,
          cycleWatt: 0.0,
          cycleWattLeft: null,
          cycleWattRight: null,
          temp: null,
          equipmentResistanceWeightsKg: null,
          equipmentIncline: null,
          localPressure: null,
          seaLevelPressure: null,
          gpsHorizontalAccuracyMeter: null,
          gpsVerticalAccuracyMeter: null,
          satellitesSignalStrength: [],
          altimeterRawMeter: null,
          levelOfDifficulty: null,
          feedbackWatt: null,
        },
        {
          pointSecond: 56,
          latitudeDegrees: '24.1237985',
          longitudeDegrees: '120.6606068',
          altitudeMeters: '192.8',
          distanceMeters: '0.7',
          elevGainMeters: 0.0,
          elevLossMeters: 0.0,
          heartRateBpm: 127.0,
          speed: 0.0,
          elevGainSpeed: null,
          elevLossSpeed: null,
          cycleCadence: 0.0,
          cycleWatt: 0.0,
          cycleWattLeft: null,
          cycleWattRight: null,
          temp: null,
          equipmentResistanceWeightsKg: null,
          equipmentIncline: null,
          localPressure: null,
          seaLevelPressure: null,
          gpsHorizontalAccuracyMeter: null,
          gpsVerticalAccuracyMeter: null,
          satellitesSignalStrength: [],
          altimeterRawMeter: null,
          levelOfDifficulty: null,
          feedbackWatt: null,
        },
        {
          pointSecond: 59,
          latitudeDegrees: '24.1237986',
          longitudeDegrees: '120.6606072',
          altitudeMeters: '192.8',
          distanceMeters: '0.7',
          elevGainMeters: 0.0,
          elevLossMeters: 0.0,
          heartRateBpm: 124.0,
          speed: 0.0,
          elevGainSpeed: null,
          elevLossSpeed: null,
          cycleCadence: 0.0,
          cycleWatt: 0.0,
          cycleWattLeft: null,
          cycleWattRight: null,
          temp: null,
          equipmentResistanceWeightsKg: null,
          equipmentIncline: null,
          localPressure: null,
          seaLevelPressure: null,
          gpsHorizontalAccuracyMeter: null,
          gpsVerticalAccuracyMeter: null,
          satellitesSignalStrength: [],
          altimeterRawMeter: null,
          levelOfDifficulty: null,
          feedbackWatt: null,
        },
        {
          pointSecond: 62,
          latitudeDegrees: '24.1237984',
          longitudeDegrees: '120.6606076',
          altitudeMeters: '192.8',
          distanceMeters: '0.7',
          elevGainMeters: 0.0,
          elevLossMeters: 0.0,
          heartRateBpm: 120.0,
          speed: 0.0,
          elevGainSpeed: null,
          elevLossSpeed: null,
          cycleCadence: 0.0,
          cycleWatt: 0.0,
          cycleWattLeft: null,
          cycleWattRight: null,
          temp: null,
          equipmentResistanceWeightsKg: null,
          equipmentIncline: null,
          localPressure: null,
          seaLevelPressure: null,
          gpsHorizontalAccuracyMeter: null,
          gpsVerticalAccuracyMeter: null,
          satellitesSignalStrength: [],
          altimeterRawMeter: null,
          levelOfDifficulty: null,
          feedbackWatt: null,
        },
        {
          pointSecond: 65,
          latitudeDegrees: '24.1237985',
          longitudeDegrees: '120.6606081',
          altitudeMeters: '192.8',
          distanceMeters: '0.7',
          elevGainMeters: 0.0,
          elevLossMeters: 0.0,
          heartRateBpm: 122.0,
          speed: 0.0,
          elevGainSpeed: null,
          elevLossSpeed: null,
          cycleCadence: 0.0,
          cycleWatt: 0.0,
          cycleWattLeft: null,
          cycleWattRight: null,
          temp: null,
          equipmentResistanceWeightsKg: null,
          equipmentIncline: null,
          localPressure: null,
          seaLevelPressure: null,
          gpsHorizontalAccuracyMeter: null,
          gpsVerticalAccuracyMeter: null,
          satellitesSignalStrength: [],
          altimeterRawMeter: null,
          levelOfDifficulty: null,
          feedbackWatt: null,
        },
        {
          pointSecond: 68,
          latitudeDegrees: '24.1237986',
          longitudeDegrees: '120.6606086',
          altitudeMeters: '192.8',
          distanceMeters: '0.7',
          elevGainMeters: 0.0,
          elevLossMeters: 0.0,
          heartRateBpm: 124.0,
          speed: 0.0,
          elevGainSpeed: null,
          elevLossSpeed: null,
          cycleCadence: 0.0,
          cycleWatt: 0.0,
          cycleWattLeft: null,
          cycleWattRight: null,
          temp: null,
          equipmentResistanceWeightsKg: null,
          equipmentIncline: null,
          localPressure: null,
          seaLevelPressure: null,
          gpsHorizontalAccuracyMeter: null,
          gpsVerticalAccuracyMeter: null,
          satellitesSignalStrength: [],
          altimeterRawMeter: null,
          levelOfDifficulty: null,
          feedbackWatt: null,
        },
        {
          pointSecond: 71,
          latitudeDegrees: '24.1237988',
          longitudeDegrees: '120.6606088',
          altitudeMeters: '192.8',
          distanceMeters: '0.7',
          elevGainMeters: 0.0,
          elevLossMeters: 0.0,
          heartRateBpm: 125.0,
          speed: 0.0,
          elevGainSpeed: null,
          elevLossSpeed: null,
          cycleCadence: 0.0,
          cycleWatt: 0.0,
          cycleWattLeft: null,
          cycleWattRight: null,
          temp: null,
          equipmentResistanceWeightsKg: null,
          equipmentIncline: null,
          localPressure: null,
          seaLevelPressure: null,
          gpsHorizontalAccuracyMeter: null,
          gpsVerticalAccuracyMeter: null,
          satellitesSignalStrength: [],
          altimeterRawMeter: null,
          levelOfDifficulty: null,
          feedbackWatt: null,
        },
        {
          pointSecond: 74,
          latitudeDegrees: '24.1237988',
          longitudeDegrees: '120.6606091',
          altitudeMeters: '192.8',
          distanceMeters: '0.7',
          elevGainMeters: 0.0,
          elevLossMeters: 0.0,
          heartRateBpm: 108.0,
          speed: 0.0,
          elevGainSpeed: null,
          elevLossSpeed: null,
          cycleCadence: 0.0,
          cycleWatt: 0.0,
          cycleWattLeft: null,
          cycleWattRight: null,
          temp: null,
          equipmentResistanceWeightsKg: null,
          equipmentIncline: null,
          localPressure: null,
          seaLevelPressure: null,
          gpsHorizontalAccuracyMeter: null,
          gpsVerticalAccuracyMeter: null,
          satellitesSignalStrength: [],
          altimeterRawMeter: null,
          levelOfDifficulty: null,
          feedbackWatt: null,
        },
      ],
    },
    {
      activityInfoLayer: {
        atmSensorStatus: 0,
        avgHeartRateBpm: 99,
        avgTemp: null,
        calories: 403,
        gpsSensorStatus: 0,
        gravitySensorStatus: 0,
        gyroSensorStatus: 0,
        maxHeartRateBpm: 128,
        maxTemp: null,
        minTemp: null,
        ohrSensorStatus: 1,
        pluginAntSensorName: [],
        pluginBluetoothSensorName: [],
        resolutionSeconds: 3,
        startTime: '2022-09-16T19:37:27.000+08:00',
        tempSensorStatus: 1,
        totalActivityLapOrSet: 1,
        totalActivitySecond: 4449,
        totalLapOrSet: 0,
        totalPoint: 1484,
        totalRestLapOrSet: 0,
        totalRestSecond: 0,
        totalSecond: 4449,
        type: '101',
        totalHrZone0Second: 15,
        totalHrZone1Second: 0,
        totalHrZone2Second: 0,
        totalHrZone3Second: 0,
        totalHrZone4Second: 0,
        totalHrZone5Second: 0,
      },
      activityLapLayer: [
        {
          dispName: '',
          lapAvgHeartRateBpm: 99,
          lapIndex: 1,
          lapStartSecondPoint: 0,
          lapTotalSecond: '4449',
          type: '0',
        },
      ],
      activityPointLayer: [
        {
          heartRateBpm: 71,
          pointSecond: 3,
          temp: 0,
        },
        {
          heartRateBpm: 101,
          pointSecond: 6,
          temp: 0,
        },
      ],
      fileInfo: {
        author: "vincent_shih's?userId=1",
        branch: 20,
        brand: '',
        class: '',
        company: '',
        countryRegion: 'TW',
        createFrom: 'iOS Connect BETA:4',
        creationDate: '2022-09-16T19:38:38.000+08:00',
        creationTimeZone: '+08:00',
        creationUnixTimeStamp: '',
        dispName: '休息轉換',
        editDate: '2022-09-16T19:38:38.000+08:00',
        equipmentFwCode: '0.0.1',
        equipmentFwName: '',
        equipmentHwCode: 0,
        equipmentHwName: 62,
        equipmentSN: ['C05WB002010007'],
        exampleFormat: '',
        fileId: 6640,
        language: 'zh',
        location: 0,
        note: '',
        photo: '',
        privacy: ['1'],
        syncDate: '2022-09-16T19:38:38.000+08:00',
        tag: '',
        tagman: '',
        teacher: '',
        type: 2,
        uploadRawFileName: '',
        versionCode: '1.5.7',
        versionName: '',
        video: '',
      },
    },
    {
      fileInfo: {
        type: '2',
        fileId: 26634,
        creationDate: '2022-07-04T14:44:58.301+08:00',
        creationUnixTimeStamp: '1656917098303',
        creationTimeZone: '+08:00',
        createFrom: 'Ala Fitness?appId=4',
        countryRegion: 'TW',
        language: 'zh',
        complexId: null,
        syncDate: '2022-07-04T14:44:58.301+08:00',
        author: 'Kidin_real?userId=384',
        editDate: '2022-07-04T14:44:58.301+08:00',
        exampleFormat: null,
        versionName: '1.6.3',
        versionCode: '1',
        location: null,
        photo: '',
        video: null,
        tag: [],
        tagman: [],
        note: null,
        privacy: ['1', '3', '4', '99'],
        teacher: null,
        class: null,
        brand: null,
        company: null,
        dispName: '\u5212\u8239\u6a5f',
        equipmentSN: ['C01R7000QQ1234'],
        equipmentFwName: null,
        equipmentFwCode: null,
        equipmentHwName: null,
        equipmentHwCode: null,
        branch: null,
        uploadRawFileName: '874dc1523561226f77d7b44bcf7d1a3c',
        fileGroupId: null,
        cloudRunMapId: null,
        matchedPlanId: null,
      },
      activityInfoLayer: {
        type: '6',
        resolutionSeconds: 3,
        startTime: '2022-07-04T14:44:18.269+08:00',
        pluginBluetoothSensorName: ['C01R7000QQ1234'],
        pluginAntSensorName: [],
        totalPoint: 11,
        totalLapOrSet: 2,
        totalActivityLapOrSet: 2,
        totalRestLapOrSet: 0,
        totalSecond: 30,
        totalActivitySecond: 30,
        totalRestSecond: 0,
        totalDistanceMeters: 42.0,
        avgHeartRateBpm: 0,
        maxHeartRateBpm: 0,
        avgSpeed: 5.1,
        maxSpeed: 5.1,
        calories: 6.28333,
        rowingAvgCadence: 50,
        rowingMaxCadence: 50,
        mets: null,
        avgTemp: null,
        maxTemp: null,
        minTemp: null,
        avgMoveSpeed: 5.1,
        equipmentAvgResistanceWeightsKg: 8.0,
        equipmentMaxResistanceWeightsKg: 8.0,
        equipmentAvgIncline: null,
        equipmentMaxIncline: null,
        rowingAvgWatt: 142.0,
        rowingMaxWatt: 142.0,
        totalPulls: 0.0,
        gpsSensorStatus: null,
        ohrSensorStatus: null,
        gravitySensorStatus: null,
        tempSensorStatus: null,
        atmSensorStatus: null,
        gyroSensorStatus: null,
        complexActivity: null,
        avgSwolf: null,
        bestSwolf: null,
        totalHrZone0Second: 30,
        totalHrZone1Second: 0,
        totalHrZone2Second: 0,
        totalHrZone3Second: 0,
        totalHrZone4Second: 0,
        totalHrZone5Second: 0,
        resolutionMillisecondStatus: 0,
        subtype: 0,
        personalizedActivityIntelligence: null,
        totalFeedbackEnergy: null,
      },
      activityLapLayer: [
        {
          type: '0',
          dispName: '',
          lapStartTime: null,
          lapStartSecondPoint: 1,
          lapTotalSecond: '26',
          lapTotalDistanceMeters: 36.6,
          lapAvgHeartRateBpm: 0.0,
          lapAvgSpeed: 5.1,
          lapEquipmentAvgResistanceWeightsKg: 8.0,
          lapEquipmentAvgIncline: null,
          lapRowingAvgWatt: 142.0,
          lapRowingAvgCadence: 50.0,
          lapTotalPulls: null,
          lapElevGain: null,
          lapElevLoss: null,
          lapIndex: 1,
          lapSwolf: null,
          feedbackEnergy: null,
        },
        {
          type: '0',
          dispName: '',
          lapStartTime: null,
          lapStartSecondPoint: 9,
          lapTotalSecond: '4',
          lapTotalDistanceMeters: 5.6,
          lapAvgHeartRateBpm: 0.0,
          lapAvgSpeed: 5.1,
          lapEquipmentAvgResistanceWeightsKg: 8.0,
          lapEquipmentAvgIncline: null,
          lapRowingAvgWatt: 142.0,
          lapRowingAvgCadence: 50.0,
          lapTotalPulls: null,
          lapElevGain: null,
          lapElevLoss: null,
          lapIndex: 2,
          lapSwolf: null,
          feedbackEnergy: null,
        },
      ],
      activityPointLayer: [
        {
          pointSecond: 2,
          distanceMeters: '2.8',
          heartRateBpm: 0.0,
          speed: 5.1,
          rowingCadence: 50.0,
          temp: null,
          equipmentResistanceWeightsKg: 8.0,
          equipmentIncline: null,
          rowingWatt: 142.0,
          localPressure: null,
          seaLevelPressure: null,
          gpsHorizontalAccuracyMeter: null,
          gpsVerticalAccuracyMeter: null,
          satellitesSignalStrength: [],
          altimeterRawMeter: null,
          levelOfDifficulty: null,
          feedbackWatt: null,
        },
        {
          pointSecond: 5,
          distanceMeters: '7.0',
          heartRateBpm: 0.0,
          speed: 5.1,
          rowingCadence: 50.0,
          temp: null,
          equipmentResistanceWeightsKg: 8.0,
          equipmentIncline: null,
          rowingWatt: 142.0,
          localPressure: null,
          seaLevelPressure: null,
          gpsHorizontalAccuracyMeter: null,
          gpsVerticalAccuracyMeter: null,
          satellitesSignalStrength: [],
          altimeterRawMeter: null,
          levelOfDifficulty: null,
          feedbackWatt: null,
        },
        {
          pointSecond: 8,
          distanceMeters: '11.3',
          heartRateBpm: 0.0,
          speed: 5.1,
          rowingCadence: 50.0,
          temp: null,
          equipmentResistanceWeightsKg: 8.0,
          equipmentIncline: null,
          rowingWatt: 142.0,
          localPressure: null,
          seaLevelPressure: null,
          gpsHorizontalAccuracyMeter: null,
          gpsVerticalAccuracyMeter: null,
          satellitesSignalStrength: [],
          altimeterRawMeter: null,
          levelOfDifficulty: null,
          feedbackWatt: null,
        },
        {
          pointSecond: 11,
          distanceMeters: '15.5',
          heartRateBpm: 0.0,
          speed: 5.1,
          rowingCadence: 50.0,
          temp: null,
          equipmentResistanceWeightsKg: 8.0,
          equipmentIncline: null,
          rowingWatt: 142.0,
          localPressure: null,
          seaLevelPressure: null,
          gpsHorizontalAccuracyMeter: null,
          gpsVerticalAccuracyMeter: null,
          satellitesSignalStrength: [],
          altimeterRawMeter: null,
          levelOfDifficulty: null,
          feedbackWatt: null,
        },
        {
          pointSecond: 14,
          distanceMeters: '19.7',
          heartRateBpm: 0.0,
          speed: 5.1,
          rowingCadence: 50.0,
          temp: null,
          equipmentResistanceWeightsKg: 8.0,
          equipmentIncline: null,
          rowingWatt: 142.0,
          localPressure: null,
          seaLevelPressure: null,
          gpsHorizontalAccuracyMeter: null,
          gpsVerticalAccuracyMeter: null,
          satellitesSignalStrength: [],
          altimeterRawMeter: null,
          levelOfDifficulty: null,
          feedbackWatt: null,
        },
        {
          pointSecond: 17,
          distanceMeters: '23.9',
          heartRateBpm: 0.0,
          speed: 5.1,
          rowingCadence: 50.0,
          temp: null,
          equipmentResistanceWeightsKg: 8.0,
          equipmentIncline: null,
          rowingWatt: 142.0,
          localPressure: null,
          seaLevelPressure: null,
          gpsHorizontalAccuracyMeter: null,
          gpsVerticalAccuracyMeter: null,
          satellitesSignalStrength: [],
          altimeterRawMeter: null,
          levelOfDifficulty: null,
          feedbackWatt: null,
        },
        {
          pointSecond: 20,
          distanceMeters: '28.2',
          heartRateBpm: 0.0,
          speed: 5.1,
          rowingCadence: 50.0,
          temp: null,
          equipmentResistanceWeightsKg: 8.0,
          equipmentIncline: null,
          rowingWatt: 142.0,
          localPressure: null,
          seaLevelPressure: null,
          gpsHorizontalAccuracyMeter: null,
          gpsVerticalAccuracyMeter: null,
          satellitesSignalStrength: [],
          altimeterRawMeter: null,
          levelOfDifficulty: null,
          feedbackWatt: null,
        },
        {
          pointSecond: 23,
          distanceMeters: '32.4',
          heartRateBpm: 0.0,
          speed: 5.1,
          rowingCadence: 50.0,
          temp: null,
          equipmentResistanceWeightsKg: 8.0,
          equipmentIncline: null,
          rowingWatt: 142.0,
          localPressure: null,
          seaLevelPressure: null,
          gpsHorizontalAccuracyMeter: null,
          gpsVerticalAccuracyMeter: null,
          satellitesSignalStrength: [],
          altimeterRawMeter: null,
          levelOfDifficulty: null,
          feedbackWatt: null,
        },
        {
          pointSecond: 26,
          distanceMeters: '36.6',
          heartRateBpm: 0.0,
          speed: 5.1,
          rowingCadence: 50.0,
          temp: null,
          equipmentResistanceWeightsKg: 8.0,
          equipmentIncline: null,
          rowingWatt: 142.0,
          localPressure: null,
          seaLevelPressure: null,
          gpsHorizontalAccuracyMeter: null,
          gpsVerticalAccuracyMeter: null,
          satellitesSignalStrength: [],
          altimeterRawMeter: null,
          levelOfDifficulty: null,
          feedbackWatt: null,
        },
        {
          pointSecond: 29,
          distanceMeters: '40.8',
          heartRateBpm: 0.0,
          speed: 5.1,
          rowingCadence: 50.0,
          temp: null,
          equipmentResistanceWeightsKg: 8.0,
          equipmentIncline: null,
          rowingWatt: 142.0,
          localPressure: null,
          seaLevelPressure: null,
          gpsHorizontalAccuracyMeter: null,
          gpsVerticalAccuracyMeter: null,
          satellitesSignalStrength: [],
          altimeterRawMeter: null,
          levelOfDifficulty: null,
          feedbackWatt: null,
        },
        {
          pointSecond: 30,
          distanceMeters: '42.3',
          heartRateBpm: 0.0,
          speed: 5.1,
          rowingCadence: 50.0,
          temp: null,
          equipmentResistanceWeightsKg: 8.0,
          equipmentIncline: null,
          rowingWatt: 142.0,
          localPressure: null,
          seaLevelPressure: null,
          gpsHorizontalAccuracyMeter: null,
          gpsVerticalAccuracyMeter: null,
          satellitesSignalStrength: [],
          altimeterRawMeter: null,
          levelOfDifficulty: null,
          feedbackWatt: null,
        },
      ],
    },
  ],
};
